site_name: Cloudbreak
site_url: http://sequenceiq.com/cloudbreak-deployer
theme: mkdocs
theme_dir: mkdocs_theme
dev_addr: 0.0.0.0:8000
pages:
    - Home:
        - Introduction : index.md
        - Architecture : architecture.md
        - Installation :
            - Cloudbreak Deployer: onprem.md
            - AWS Cloud Images: aws-image.md
            - GCP Cloud Images: gcp-image.md
            - OpenStack Cloud Images: openstack-image.md
        - Release Notes : releasenotes.md
    - Cloud Providers:
        - AWS :
            - Setup: aws.md
            - 'Provisioning Prerequisites': aws_pre_prov.md
            - 'Provisioning - UI': aws_cb_ui.md
            - 'Provisioning - CLI': aws_cb_shell.md
        - Azure :
            - Setup: azure.md
            - 'Provisioning Prerequisites': azure_pre_prov.md
            - 'Provisioning - UI': azure_cb_ui.md
            - 'Provisioning - CLI': azure_cb_shell.md
        - GCP :
            - Setup: gcp.md
            - 'Provisioning Prerequisites': gcp_pre_prov.md
            - 'Provisioning - UI': gcp_cb_ui.md
            - 'Provisioning - CLI': gcp_cb_shell.md
        - OpenStack :
            - Setup: openstack.md
            - 'Provisioning Prerequisites': openstack_pre_prov.md
            - 'Provisioning - UI': openstack_cb_ui.md
            - 'Provisioning - CLI': openstack_cb_shell.md
    - Reference:
        - Blueprints : blueprints.md
        - API : api.md
        - CLI/Shell : shell.md
        - Periscope : periscope.md
        - Recipes: recipes.md
        - Kerberos: kerberos.md
        - SPI: spi.md
        - Operations : operations.md
        - Migration : database.md
        - Advanced Configuration : configuration.md
        - Development : development.md
        - Changelog : changelog.md
