site_name: Cloudbreak Deployer
site_url: http://sequenceiq.com/cloudbreak-deployer
theme: mkdocs
theme_dir: mkdocs_theme
dev_addr: 0.0.0.0:8000
pages:
    - Home:
        - Introduction : index.md
        - Technology : technology.md
        - Installation :
            - On-prem: onprem.md
            - AWS: aws.md
            - Azure: azure.md
            - GCP: gcp.md
            - OpenStack: openstack.md
        - Benefits : overview.md
    - Providers:
        - AWS :
            - Deployment: aws.md
            - 'Provisioning prerequisites': aws_pre_prov.md
            - 'Provisioning - UI': aws_cb_ui.md
            - 'Provisioning - CLI': aws_cb_shell.md
        - Azure :
            - Deployment: azure.md
            - 'Provisioning prerequisites': azure_pre_prov.md
            - 'Provisioning - UI': azure_cb_ui.md
            - 'Provisioning - CLI': azure_cb_shell.md
        - GCP :
            - Deployment: gcp.md
            - 'Provisioning prerequisites': gcp_pre_prov.md
            - 'Provisioning - UI': gcp_cb_ui.md
            - 'Provisioning - CLI': gcp_cb_shell.md
        - OpenStack :
            - Deployment: openstack.md
            - 'Provisioning prerequisites': openstack_pre_prov.md
            - 'Provisioning - UI': openstack_cb_ui.md
            - 'Provisioning - CLI': openstack_cb_shell.md
    - Docs:
        - API : api.md
        - CLI : shell.md
        - Recipes: recipes.md
        - SPI: spi.md
        - Kerberos: kerberos.md
        - Operations: operations.md
        - Migration : database.md
        - Configuration : configuration.md
        - Development : development.md
        - Changelog : changelog.md
