mock:
  server:
    address: test
  image:
    catalog:
      url: https://test:9443/imagecatalog

integrationtest:
  outputdir: /it
  spark:
    sparkPoolSize: 8
  threadCount: 2
  parallel: classes
  defaultBlueprintName: hdp-small-default
  command: suites
  cleanup:
    cleanupBeforeStart: false
