mock:
  server:
    address: test.service.consul

integrationtest:
    testsuite:
      threadPoolSize: 1
    defaultBlueprintName: hdp-small-default
    outputdir: /it
    command: suites
    suiteFiles: /it/src/main/resources/testsuites/mock/mock-clustercreate-salt.yaml,/it/src/main/resources/testsuites/mock/mock-scaling-salt.yaml
    cleanup:
      cleanupBeforeStart: true
