mock:
  server:
    address: test.service.consul
  image:
    catalog:
      url: https://test.service.consul:9443/imagecatalog

integrationtest:
    testsuite:
      threadPoolSize: 1
      pollingInterval: 1000
    defaultClusterDefinitionName: hdp-small-default
    outputdir: /it
    command: suites
    cleanup:
      cleanupBeforeStart: true
